### PR TITLE
Possible fix for issue #15 and #13.

### PR DESCRIPTION
**Pull request by Pshpdesu**
Also login with refresh tokens are working now, but need more testing.

### CODE REVIEW

**Comment by Pshpdesu** [comment]
To find solution of the problems, I looked up the other unofficial pixiv client (pxview: https://github.com/alphasp/pxview) and api for JS (https://github.com/alphasp/pixiv-api-client). Also reorganize some stuff, like group up string constants in separate class.

**Comment by Pshpdesu** [comment]
Oh, and I changed client credentials to a newer one from that projects, what I linked earlier. I'd like to test old ones. Keep a pull request for later.

**Comment by Pshpdesu** [comment]
Test authorization with old client information and credentials. Working fine. Seems like there's no need for device token in current version of pixiv's api. Maybe delete it from function parameters of just set it default value to empty?

**Comment by yinyue200** [comment]
I think it shouldn’t be empty or something like it 😂

**Comment by Pshpdesu** [comment]
Hm, right now tried to press update button and this doesn't work 🤔. Need more testing.

**Comment by Pshpdesu** [comment]
Seems like SendRequestWithAuthAsync doesn't check if access token is valid. Am I wrong?

**Comment by Pshpdesu** [comment]
Old credentials doesn't work

**Comment by Pshpdesu** [comment]
Added check for requests, what need (and don't need ＞﹏＜) access tokens

**Comment by Pshpdesu** [comment]
@SakuraNeko What do you think?

**Comment by Pshpdesu** [comment]
Windows 10 below 16299 version can't decode webp pictures, so I played around with OS version and other api parameters until get requests start sending normal jpeg pictures. Authorization with refresh token still works.

**Pull request merged**
